# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fabric_pb2 as fabric__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fabric_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub:
    """─────────────────────────────────────────────────────────────────────────────
    Service 1: ControlPlane
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAndRequestKey = channel.unary_unary(
                '/chorus.ControlPlane/RegisterAndRequestKey',
                request_serializer=fabric__pb2.PodRegistration.SerializeToString,
                response_deserializer=fabric__pb2.SessionKeyBundle.FromString,
                _registered_method=True)
        self.RequestOrthogonalProjections = channel.unary_unary(
                '/chorus.ControlPlane/RequestOrthogonalProjections',
                request_serializer=fabric__pb2.KeyRequest.SerializeToString,
                response_deserializer=fabric__pb2.ProjectionBundle.FromString,
                _registered_method=True)
        self.GetRelayInstruction = channel.unary_unary(
                '/chorus.ControlPlane/GetRelayInstruction',
                request_serializer=fabric__pb2.KeyRequest.SerializeToString,
                response_deserializer=fabric__pb2.RelayInstruction.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/chorus.ControlPlane/RotateKey',
                request_serializer=fabric__pb2.KeyRequest.SerializeToString,
                response_deserializer=fabric__pb2.SessionKeyBundle.FromString,
                _registered_method=True)
        self.GetSessionKey = channel.unary_unary(
                '/chorus.ControlPlane/GetSessionKey',
                request_serializer=fabric__pb2.KeyRequest.SerializeToString,
                response_deserializer=fabric__pb2.SessionKeyBundle.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """─────────────────────────────────────────────────────────────────────────────
    Service 1: ControlPlane
    ─────────────────────────────────────────────────────────────────────────────
    """

    def RegisterAndRequestKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOrthogonalProjections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelayInstruction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAndRequestKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAndRequestKey,
                    request_deserializer=fabric__pb2.PodRegistration.FromString,
                    response_serializer=fabric__pb2.SessionKeyBundle.SerializeToString,
            ),
            'RequestOrthogonalProjections': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOrthogonalProjections,
                    request_deserializer=fabric__pb2.KeyRequest.FromString,
                    response_serializer=fabric__pb2.ProjectionBundle.SerializeToString,
            ),
            'GetRelayInstruction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelayInstruction,
                    request_deserializer=fabric__pb2.KeyRequest.FromString,
                    response_serializer=fabric__pb2.RelayInstruction.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=fabric__pb2.KeyRequest.FromString,
                    response_serializer=fabric__pb2.SessionKeyBundle.SerializeToString,
            ),
            'GetSessionKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionKey,
                    request_deserializer=fabric__pb2.KeyRequest.FromString,
                    response_serializer=fabric__pb2.SessionKeyBundle.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chorus.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chorus.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """─────────────────────────────────────────────────────────────────────────────
    Service 1: ControlPlane
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def RegisterAndRequestKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.ControlPlane/RegisterAndRequestKey',
            fabric__pb2.PodRegistration.SerializeToString,
            fabric__pb2.SessionKeyBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestOrthogonalProjections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.ControlPlane/RequestOrthogonalProjections',
            fabric__pb2.KeyRequest.SerializeToString,
            fabric__pb2.ProjectionBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelayInstruction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.ControlPlane/GetRelayInstruction',
            fabric__pb2.KeyRequest.SerializeToString,
            fabric__pb2.RelayInstruction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.ControlPlane/RotateKey',
            fabric__pb2.KeyRequest.SerializeToString,
            fabric__pb2.SessionKeyBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chorus.ControlPlane/GetSessionKey',
            fabric__pb2.KeyRequest.SerializeToString,
            fabric__pb2.SessionKeyBundle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TargetPodStub:
    """─────────────────────────────────────────────────────────────────────────────
    Service 2: TargetPod  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSignal = channel.stream_stream(
                '/chorus.TargetPod/StreamSignal',
                request_serializer=fabric__pb2.TensorPayload.SerializeToString,
                response_deserializer=fabric__pb2.SignalAck.FromString,
                _registered_method=True)


class TargetPodServicer:
    """─────────────────────────────────────────────────────────────────────────────
    Service 2: TargetPod  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    def StreamSignal(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TargetPodServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSignal': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSignal,
                    request_deserializer=fabric__pb2.TensorPayload.FromString,
                    response_serializer=fabric__pb2.SignalAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chorus.TargetPod', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chorus.TargetPod', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TargetPod:
    """─────────────────────────────────────────────────────────────────────────────
    Service 2: TargetPod  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def StreamSignal(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chorus.TargetPod/StreamSignal',
            fabric__pb2.TensorPayload.SerializeToString,
            fabric__pb2.SignalAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RelayNodeStub:
    """─────────────────────────────────────────────────────────────────────────────
    Service 3: RelayNode  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RelayStream = channel.stream_stream(
                '/chorus.RelayNode/RelayStream',
                request_serializer=fabric__pb2.TensorPayload.SerializeToString,
                response_deserializer=fabric__pb2.RelayAck.FromString,
                _registered_method=True)


class RelayNodeServicer:
    """─────────────────────────────────────────────────────────────────────────────
    Service 3: RelayNode  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    def RelayStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RelayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RelayStream,
                    request_deserializer=fabric__pb2.TensorPayload.FromString,
                    response_serializer=fabric__pb2.RelayAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chorus.RelayNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chorus.RelayNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelayNode:
    """─────────────────────────────────────────────────────────────────────────────
    Service 3: RelayNode  –  bidirectional streaming
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def RelayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/chorus.RelayNode/RelayStream',
            fabric__pb2.TensorPayload.SerializeToString,
            fabric__pb2.RelayAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
